### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by marcuscraske** [tobyweston/unicorn-hat#1]
I have tried using parts of this repo for a project and I am receiving the following issue:

Starting program: /usr/bin/java -jar rpi-test.jar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76422470 (LWP 7912)]
[New Thread 0x670f1470 (LWP 7913)]
[New Thread 0x67071470 (LWP 7914)]
[New Thread 0x67021470 (LWP 7915)]
[New Thread 0x66e5a470 (LWP 7916)]
[New Thread 0x66e0a470 (LWP 7917)]
[New Thread 0x66d8a470 (LWP 7918)]
[New Thread 0x66bff470 (LWP 7919)]
lib path: /home/limpygnome/java/libws2811.so
loaded

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x76422470 (LWP 7912)]
ws2811_led_set (channel=<optimized out>, lednum=0, color=16777215) at rpi_ws281x_wrap.c:213
213         channel->leds[lednum] = color;

With the following code:
 AdafruitNeoPixel adafruitNeoPixel = new AdafruitNeoPixel(59, 18, 800000, 5, false, 255, 0);
        adafruitNeoPixel.setBrightness(1.0);
        for (int i = 0; i < 25; i++)
            adafruitNeoPixel.setPixelColor(i, (short) 255, (short)255, (short)255);
        adafruitNeoPixel.show();
        adafruitNeoPixel.cleanup();

The issue is the call to ws2811_led_set for the very first pixel.

Any suggestions/ideas?

**Comment by tobyweston** [comment]
sorry, no ideas here.

Are you using the project verbatim? you said "parts of it"?

You can always go back to the originating C code from pimoroni/unicorn-hat et al and avoid the Java layer

**Comment by marcuscraske** [comment]
I'm not sure how, but I got it working eventually. I suspect I was not linking the libraries correctly. I've used your build scripts and found them very useful, thank you! Repo starred <3.
